default_language_version:
  python: python3.10

files: app

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-merge-conflict
      - id: detect-private-key
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
        types: [python]
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
        args: [--remove]
      - id: mixed-line-ending
        args: [--fix=lf]
        types: [python]
      - id: requirements-txt-fixer
        args: [filenames=requirements.txt]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn
      - id: python-use-type-annotations
      - id: text-unicode-replacement-char

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.34.0
    hooks:
      - id: pyupgrade
        args: [--py39-plus]

  - repo: https://github.com/google/yapf
    rev: v0.32.0
    hooks:
      - id: yapf

  - repo: https://github.com/pycqa/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --remove-unused-variables
          - --ignore-init-module-imports

  - repo: https://github.com/pycqa/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args:
          - --aggregate=file
          - -iii
          - -ll
        require_serial: true

  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.4
    hooks:
      - id: vulture
        args:
          - --min-confidence=100
          - app

